export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const ADMIN_GET_LIST_MOD = "ADMIN_GET_LIST_MOD";
export const ADMIN_GET_LIST_MOD_SUCCEED = "ADMIN_GET_LIST_MOD_SUCCEED";
export const ADMIN_GET_LIST_MOD_FAILED = "ADMIN_GET_LIST_MOD_FAILED";

export const ADMIN_GET_LIST_COMPANY = "ADMIN_GET_LIST_COMPANY";
export const ADMIN_GET_LIST_COMPANY_SUCCEED = "ADMIN_GET_LIST_COMPANY_SUCCEED";
export const ADMIN_GET_LIST_COMPANY_FAILED = "ADMIN_GET_LIST_COMPANY_FAILED";

export const ADMIN_GET_LIST_ITER = "ADMIN_GET_LIST_ITER";
export const ADMIN_GET_LIST_ITER_SUCCEED = "ADMIN_GET_LIST_ITER_SUCCEED";
export const ADMIN_GET_LIST_ITER_FAILED = "ADMIN_GET_LIST_ITER_FAILED";

export const ADD_MOD_API = "ADD_MOD_API";
export const ADD_MOD_API_SUCCEED = "ADD_MOD_API_SUCCEED";
export const ADD_MOD_API_FAILED = "ADD_MOD_API_FAILED";

export const DELETE_MOD_API = "DELETE_MOD_API";
export const DELETE_MOD_API_SUCCEED = "DELETE_MOD_API_SUCCEED";
export const DELETE_MOD_API_FAILED = "DELETE_MOD_API_FAILED";

export const ADMIN_GET_MOD_PERMISSIONS = "ADMIN_GET_MOD_PERMISSIONS";
export const ADMIN_GET_MOD_PERMISSIONS_SUCCEED = "ADMIN_GET_MOD_PERMISSIONS_SUCCEED";
export const ADMIN_GET_MOD_PERMISSIONS_FAILED = "ADMIN_GET_MOD_PERMISSIONS_FAILED";

export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";
export const GET_ROLE_PERMISSIONS_SUCCEED = "GET_ROLE_PERMISSIONS_SUCCEED";
export const GET_ROLE_PERMISSIONS_FAILED = "GET_ROLE_PERMISSIONS_FAILED";