export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const ADMIN_GET_LIST_MOD = "ADMIN_GET_LIST_MOD";
export const ADMIN_GET_LIST_MOD_SUCCEED = "ADMIN_GET_LIST_MOD_SUCCEED";
export const ADMIN_GET_LIST_MOD_FAILED = "ADMIN_GET_LIST_MOD_FAILED";

export const ADMIN_GET_LIST_COMPANY = "ADMIN_GET_LIST_COMPANY";
export const ADMIN_GET_LIST_COMPANY_SUCCEED = "ADMIN_GET_LIST_COMPANY_SUCCEED";
export const ADMIN_GET_LIST_COMPANY_FAILED = "ADMIN_GET_LIST_COMPANY_FAILED";

export const ADMIN_GET_LIST_ITER = "ADMIN_GET_LIST_ITER";
export const ADMIN_GET_LIST_ITER_SUCCEED = "ADMIN_GET_LIST_ITER_SUCCEED";
export const ADMIN_GET_LIST_ITER_FAILED = "ADMIN_GET_LIST_ITER_FAILED";

export const ADD_MOD_API = "ADD_MOD_API";
export const ADD_MOD_API_SUCCEED = "ADD_MOD_API_SUCCEED";
export const ADD_MOD_API_FAILED = "ADD_MOD_API_FAILED";

export const DELETE_MOD_API = "DELETE_MOD_API";
export const DELETE_MOD_API_SUCCEED = "DELETE_MOD_API_SUCCEED";
export const DELETE_MOD_API_FAILED = "DELETE_MOD_API_FAILED";

export const DELETE_COMPANY_API = "DELETE_COMPANY_API";
export const DELETE_COMPANY_API_SUCCEED = "DELETE_COMPANY_API_SUCCEED";
export const DELETE_COMPANY_API_FAILED = "DELETE_COMPANY_API_FAILED";

export const DELETE_ITER_API = "DELETE_ITER_API";
export const DELETE_ITER_API_SUCCEED = "DELETE_ITER_API_SUCCEED";
export const DELETE_ITER_API_FAILED = "DELETE_ITER_API_FAILED";

export const ADMIN_GET_MOD_PERMISSIONS = "ADMIN_GET_MOD_PERMISSIONS";
export const ADMIN_GET_MOD_PERMISSIONS_SUCCEED = "ADMIN_GET_MOD_PERMISSIONS_SUCCEED";
export const ADMIN_GET_MOD_PERMISSIONS_FAILED = "ADMIN_GET_MOD_PERMISSIONS_FAILED";

export const ADMIN_UPDATE_MOD_PERMISSIONS = "ADMIN_UPDATE_MOD_PERMISSIONS";
export const ADMIN_UPDATE_MOD_PERMISSIONS_SUCCEED = "ADMIN_UPDATE_MOD_PERMISSIONS_SUCCEED";
export const ADMIN_UPDATE_MOD_PERMISSIONS_FAILED = "ADMIN_UPDATE_MOD_PERMISSIONS_FAILED";

export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";
export const GET_ROLE_PERMISSIONS_SUCCEED = "GET_ROLE_PERMISSIONS_SUCCEED";
export const GET_ROLE_PERMISSIONS_FAILED = "GET_ROLE_PERMISSIONS_FAILED";

export const UPDATE_ROLE_PERMISSIONS_API = "UPDATE_ROLE_PERMISSIONS_API";
export const UPDATE_ROLE_PERMISSIONS_API_SUCCEED = "UPDATE_ROLE_PERMISSIONS_API_SUCCEED";
export const UPDATE_ROLE_PERMISSIONS_API_FAILED = "UPDATE_ROLE_PERMISSIONS_API_FAILED";

export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCEED = "GET_POSTS_SUCCEED";
export const GET_POSTS_FAILED = "GET_POSTS_FAILED";

export const GET_UNACCEPTED_POST = "GET_UNACCEPTED_POST";
export const GET_UNACCEPTED_POST_SUCCEED = "GET_UNACCEPTED_POST_SUCCEED";
export const GET_UNACCEPTED_POST_FAILED = "GET_UNACCEPTED_POST_FAILED";

export const DELETE_POST_API = "DELETE_POST_API";
export const DELETE_POST_API_SUCCEED = "DELETE_POST_API_SUCCEED";
export const DELETE_POST_API_FAILED = "DELETE_POST_API_FAILED";

export const APPROVE_POST_API = "APPROVE_POST_API";
export const APPROVE_POST_API_SUCCEED = "APPROVE_POST_API_SUCCEED";
export const APPROVE_POST_API_FAILED = "APPROVE_POST_API_FAILED";