export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const ADMIN_GET_LIST_MOD = "ADMIN_GET_LIST_MOD";
export const ADMIN_GET_LIST_MOD_SUCCEED = "ADMIN_GET_LIST_MOD_SUCCEED";
export const ADMIN_GET_LIST_MOD_FAILED = "ADMIN_GET_LIST_MOD_FAILED";

export const ADMIN_GET_LIST_COMPANY = "ADMIN_GET_LIST_COMPANY";
export const ADMIN_GET_LIST_COMPANY_SUCCEED = "ADMIN_GET_LIST_COMPANY_SUCCEED";
export const ADMIN_GET_LIST_COMPANY_FAILED = "ADMIN_GET_LIST_COMPANY_FAILED";

export const ADMIN_GET_LIST_ITER = "ADMIN_GET_LIST_ITER";
export const ADMIN_GET_LIST_ITER_SUCCEED = "ADMIN_GET_LIST_ITER_SUCCEED";
export const ADMIN_GET_LIST_ITER_FAILED = "ADMIN_GET_LIST_ITER_FAILED";

