export const technicalSkill = [
  { label: "Android", value: "Android" },
  { label: "C", value: "C" },
  { label: "C++", value: "C++" },
  { label: "C#", value: "C#" },
  { label: "CSS", value: "CSS" },
  { label: "Database", value: "Database" },
  { label: "Java", value: "Java" },
  { label: "Javascript", value: "Javascript" },
  { label: "Python", value: "Python" },
  { label: "PHP", value: "PHP" },
  { label: "HTML", value: "HTML" },
  { label: "Ruby", value: "Ruby" },
  { label: "Visual Basic", value: "Visual Basic" },
  { label: "Dart", value: "Dart" },
  { label: "Swift", value: "Swift" },
  { label: "Go", value: "Go" },
  { label: "R", value: "R" },
  { label: "React", value: "React" },
  { label: "Angular", value: "Angular" },
  { label: "Vue", value: "Vue" },
  { label: ".NET", value: ".NET" },
  { label: "NodeJS", value: "NodeJS" },
  { label: "SQL", value: "SQL" },
  { label: "Testing", value: "Testing" },
];
